apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-test
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworld-test
    spec:
      containers:
      - name: k8s-demo
        image: sanalinasu/k8s-demo
        ports:
        - name: nodejs-port
          containerPort: 3000
